language: node_js

node_js:
  - 10

before_install:
  - npm install -g @commitlint/travis-cli

install:
  - npm install
  - npm install -g codecov
  - npm install -g eslint
  - commitlint-travis

script:
  - npm run lint
  - npm run test:ci
  - codecov

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
